GET http://localhost:3000/users

###
GET http://localhost:3000/users/6a9b2cc8f705477fa7fbf9d9

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Greg",
  "lastName": "Gregory",
  "email": "GregGreg@example.com",
  "favoriteColor": "Purple",
  "birthday": "2001-04-07"
}

###
PUT http://localhost:3000/users/6a9b2cc8f705477fa7fbf9d9
Content-Type: application/json

{
  "firstName": "Henrique",
  "lastName": "Gregorio",
  "email": "GregGreg@example.com",
  "favoriteColor": "black",
  "birthday": "2001-04-07"
}

###
DELETE http://localhost:3000/users/6a9b2cc8f705477fa7fbf9d9